### ISSUE TITLE
"Unable to leverage the go-micro since the context package is not supported appropriately in Go version 1.7"

### ISSUE THREAD

**Issue by asim** [Ch3ck/go-serve#6]
This is a fairly inaccurate statement. Go-micro makes use of "golang.org/x/net/context" which works regardless of which version of Go you are using. The inability to use the native "context" package Context in place of "golang.org/x/net/context" Context is just because of the type system of Go. You should be making use of "golang.org/x/net/context" in that case. The same can be said for grpc.

**Comment by Ch3ck** [comment]
Yeah,  @asim I tried using golang/x/net/context" It was reporting some issues. So I decided to move to stlib context. However after rebuilding the golang/x/net/context package. Everything works fine.

**Comment by asim** [comment]
Would appreciate the removal of the comment since it's inaccurate.

**Comment by Ch3ck** [comment]
Yeah, will do :+1:
